[tox]
requires = tox>=4
envlist = dep{0.7,0.15,0.15.1b1}

[testenv]
dependency_groups =
    test
deps =
    pytest
    0.7: curl-cffi=>0.7,<0.8
    0.15: curl-cffi>=0.15,<0.16
    0.15.1b1: curl-cffi==0.15.1b1
commands =
    pytest {posargs}
