name: release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: ["test"]
    runs-on: ubuntu-latest
    steps:
      # fetch-depth: 0 required for uv-dynamic-versioning to read git tags
      # https://github.com/actions/checkout#fetch-depth
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"
          enable-cache: true

      - run: uv build
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist

  release:
    needs: ["build"]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
          make_latest: true
          files: artifact/*

  pypi-publish:
    needs: ["build"]
    environment:
      name: publish
      url: https://pypi.org/p/httpx-curl-cffi

    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: artifact/
