name: test

on: [push, workflow_call]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - run: |
          pdm install -G test
          pdm run test
